### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by maciejsobala** [sdd/serverless-apig-s3#1]
Hello, When I am trying to run this plugin. I got following issue:

```
  Syntax Error -------------------------------------------
 
     Unexpected identifier
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
SyntaxError: Unexpected identifier
/path_to_my_project/node_modules/serverless-apig-s3/index.js:46
    async mergeApigS3Resources() {
          ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at plugins.forEach (/path_to_my_project/node_modules/serverless/lib/classes/PluginManager.js:98:22)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/path_to_my_project/node_modules/serverless/lib/classes/PluginManager.js:97:13)
    at PluginManager.loadServicePlugins (/path_to_my_project/node_modules/serverless/lib/classes/PluginManager.js:124:10)
    at PluginManager.loadAllPlugins (/path_to_my_project/node_modules/serverless/lib/classes/PluginManager.js:93:10)
    at service.load.then (/path_to_my_project/node_modules/serverless/lib/Serverless.js:64:28)
From previous event:
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at __dirname (/path_to_my_project/node_modules/serverless/bin/serverless:15:28)
    at Object.<anonymous> (/path_to_my_project/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I am running serverless 1.10.0  My serverless.yml is just:

```
plugins:
 - serverless-apig-s3

custom:
  apigs3:
    dist: dist
```

**Comment by maciejsobala** [comment]
After a little bit of investigation I find out that I was using old version of node, which doesn't support async keyword.

**Comment by sdd** [comment]
OK, glad you solved the problem. Are you upgrading node and still using the plugin, or using something else instead?

**Comment by maciejsobala** [comment]
I updated node, and use your plugin. Works nice. I need to change few things (my `/` path should direct to lambda function), so you should expect pull request from me ;)

I run into problems with serving binary files (images). Don't know why, but they are just not working (file size is different ie). I am still investigating this problem.

**Comment by sdd** [comment]
Glad you could make use of it! If I get chance later today, I'll try serving up some different image files and see if I can reproduce the problem you are seeing.
