### ISSUE TITLE
Problem when use with serverless-python-requirements plugin

### ISSUE THREAD

**Issue by vanhongts** [sdd/serverless-apig-s3#15]
I am using serverless framework with 2 plugin serverless-python-requirements and serverless-apig-s3. But I got following issue when deploy:

```
Error: ENOENT: no such file or directory, scandir '.requirements'
    at Object.fs.readdirSync (fs.js:914:18)
    at ServerlessPythonRequirements.unlinkRequirements (/home/xyz/Documents/Serverless/example/node_modules/serverless-python-requirements/index.js:177:11)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.spawn (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:384:17)
    at Deploy.BbPromise.bind.then.then (/usr/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:120:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:110:10)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (/usr/lib/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (/usr/lib/node_modules/serverless/bin/serverless:42:50)
```

 This is my config: 

```
plugins:
   - serverless-python-requirements
   - serverless-apig-s3
 custom:
   apigs3:
     dist: client/dist
     dotFiles: true
     topFiles: true
     resourceName: static
     resourcePath: ""
```
My environment:
``` OS:                     linux
     Node Version:           7.10.1
     Serverless Version:     1.24.1
```

**Comment by bweigel** [comment]
I am not sure whether this is an issue at all. It looks like you have a problem with the serverless-python-requirements plugin. It does not find the directory or file `.requirements`. That folder should be created by that plugin. See https://www.npmjs.com/package/serverless-python-requirements#manual-invocations

**Comment by bweigel** [comment]
I have looked into this a little more and there really seems too be an issue here.
I think it has to do with the hook this plugin is using (`package:createDeploymentArtifacts`), which has been deprecated. I am working on a fix. 

Please open again @sdd
